version: "3"
services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/pismodb?useSSL=false
      - spring.datasource.username=pismo_user
      - spring.datasource.password=pismo_pass
    networks:
      - mysql-net
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    ports:
      - "3307:3306"
    networks:
      - mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pismodb
      - MYSQL_USER=pismo_user
      - MYSQL_PASSWORD=pismo_pass
networks:
  mysql-net: